artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: SemEvalWorkshop/sem_eval_2018_task_1
  local_data_file: artifacts/data_ingestion/sem_eval_2018_task_1
  extract_dir: artifacts/data_ingestion/
